schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "blender_fasthenry_extension"
version = "1.0.0"
name = "Blender FastHenry"
tagline = "Crate and Run FastHenry simulations"
maintainer = "Samer Aldhaher <contact@metalcircuits.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/samerps/BlenderFH"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["3D View", "Geometry Nodes", "Physics"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# Optional: required by some licenses.
copyright = [
  "2018 FastFieldSolvers S.R.L. http://www.fastfieldsolvers.com",
  "1996 Massachusetts Institute of Technology, Cambridge, MA.",
]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
platforms = ["windows-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
#wheels = ["./wheels/pywin32-306-cp311-cp311-win_amd64.whl"]

# Optional: add-ons can list which resources they will require:
# * files (FastFieldSolvers bundle binary distribution for Windows)
# * network (for internet access)
# * clipboard (to read and/or write the system clipboard)
# * camera (to capture photos and videos)
# * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
[permissions]
files = "Import/export CSV and INP from/to disk"
